// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:citizen/features/report/models/report.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ReportAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ReportAdapter());
  }
}
